name: build-commons-project
run-name: Build commons project

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  ARTIFACT_VERSION: 0.6.0

jobs:
  build-commons-lib:
    runs-on: self-hosted
    steps:
      - name: Set permissions
        run: docker run --rm -v "$PWD":/project bash:latest chown --recursive $(id -u):$(id -g) /project
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Build distribution
        run: docker run --rm -v "$PWD":/home/gradle/project -w /home/gradle/project gradle:jdk17 gradle -PARTIFACT_VERSION=$ARTIFACT_VERSION distribute
      - name: Set permissions
        run: docker run --rm -v "$PWD":/project bash:latest chown --recursive $(id -u):$(id -g) /project
      - name: Analyze project
        run: | 
          docker run \
          --rm \
          -v "${PWD}:/usr/src" \
          -e SONAR_SCANNER_OPTS="-Dsonar.host.url=${{ vars.SQSERVER }} -Dsonar.token=${{ secrets.SQTOKEN }} -Dsonar.projectKey=goa.systems.commons -Dsonar.sources=src/main -Dsonar.java.libraries=build/libs -Dsonar.java.binaries=build/classes -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml -Dsonar.junit.reportsPath=build/test-results -Xdiag" \
          --network host \
          sonarsource/sonar-scanner-cli
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Publish artifact
        run: |
          scp build/distributions/goa.systems.commons-$ARTIFACT_VERSION.tar.gz foo@tools.goa.systems:/tmp
          ssh foo@tools.goa.systems "bash -s" < ".github/scripts/deploymaven" "/tmp/goa.systems.commons-$ARTIFACT_VERSION.tar.gz"
          ssh foo@tools.goa.systems "rm /tmp/goa.systems.commons-$ARTIFACT_VERSION.tar.gz"
        if: ${{ github.ref == 'refs/heads/main' }}
