name: build-commons-project
run-name: Build commons project

on: [push,workflow_dispatch]

env:
  ARTIFACT_VERSION: 0.5.1

jobs:
  build-commons-lib:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Make Gradle wrapper executable
        run: |
          chmod u+x gradlew
      - name: Build distribution
        run: |
          ./gradlew \
            -PARTIFACT_VERSION=$ARTIFACT_VERSION \
            clean \
            build \
            jar \
            sourcesJar \
            javadocJar \
            exportPom \
            exportLogbackConfig \
            exportReadme \
            exportApplicationLibraries \
            exportFullSetupDependencies \
            generatePomFileForCommonsPublication \
            writeVariables \
            distribute \
            jacocoTestReport
      - name: Run SonarQube scanner
        run: |
          source ~/.sqcredentials
          sonar-scanner \
            -Dsonar.projectKey=goa.systems.commons \
            -Dsonar.sources=src/main/java \
            -Dsonar.java.libraries=build/libs \
            -Dsonar.java.binaries=build/classes \
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
            -Dsonar.junit.reportsPath=build/test-results \
            -Dsonar.host.url=$SQSERVER \
            -Dsonar.login=$SQTOKEN
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Publish artifact
        run: |
             scp build/distributions/goa.systems.commons-$ARTIFACT_VERSION.tar.gz foo@tools.goa.systems:/tmp
             ssh foo@tools.goa.systems "deployartifact /tmp/goa.systems.commons-$ARTIFACT_VERSION.tar.gz"
             ssh foo@tools.goa.systems "rm /tmp/goa.systems.commons-$ARTIFACT_VERSION.tar.gz"
        if: ${{ github.ref == 'refs/heads/main' }}