name: build-commons-project
run-name: Build commons project

on: [push,workflow_dispatch]

env:
  ARTIFACT_VERSION: 0.3.1

jobs:
  build-commons-lib:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: chmod u+x gradlew
      - run: ./gradlew -PARTIFACT_VERSION=$ARTIFACT_VERSION distribute
      - run: |
             sonar-scanner \
             -Dsonar.projectKey=goa.systems.commons \
             -Dsonar.sources=src/main/java \
             -Dsonar.java.binaries=build/classes \
             -Dsonar.host.url=https://sonarqube.dom.schrotti12.eu \
             -Dsonar.login=sqp_fc4e0f01ef74c847c23fa2f4d1914c84078c1d8b
      - run: |
             scp build/distributions/goa.systems.commons-$ARTIFACT_VERSION.tar.gz foo@tools.goa.systems:/tmp
             ssh foo@tools.goa.systems "deploymaven /tmp/goa.systems.commons-$ARTIFACT_VERSION.tar.gz goa.systems commons $ARTIFACT_VERSION"
             ssh foo@tools.goa.systems "rm /tmp/goa.systems.commons-$ARTIFACT_VERSION.tar.gz"